tikv-control: Replace `--db` with `--data-dir`
Required changes:

* Replace `--db` with `--data-dir`
* Remove `/db` from the path

```
[dvaneeden@dve-carbon tikv-0]$ tiup ctl:v5.2.2 tikv --db /home/dvaneeden/.tiup/data/SqRmWep/tikv-0/data/db size -r 2
Starting component `ctl`: /home/dvaneeden/.tiup/components/ctl/v5.2.2/ctl tikv --db /home/dvaneeden/.tiup/data/SqRmWep/tikv-0/data/db size -r 2
error: Invalid value for '--db <db>': DEPRECATED!!! Use --data-dir and --config instead
Error: exit status 1
Error: run `/home/dvaneeden/.tiup/components/ctl/v5.2.2/ctl` (wd:/home/dvaneeden/.tiup/data/SqWYNWa) failed: exit status 1
```

See also https://github.com/tikv/website/pull/307

I used this:

```
sed -i -E 's/tikv-ctl (.*)--db ([^ ]*)\/db\/?/tikv-ctl \1--data-dir \2/g' tikv-control.md
```